### ISSUE TITLE
Анализ стека технологий для фронтенда

### ISSUE THREAD

**Issue by vaddya** [ACCULA/accula#1]
[https://github.com/ACCULA/accula/wiki/Frontend-Development-Stack](https://github.com/ACCULA/accula/wiki/Frontend-Development-Stack)

**Comment by lamtev** [comment]
1. Why don't you consider Svelte framework once it becomes more and more popular?

**Comment by vaddya** [comment]
> 1. Why don't you consider Svelte framework once it becomes more and more popular?

It's [obvious](https://i.gyazo.com/bbe1e11a006df2a1bbfbfc6355b5a0e3.png). Actually, we could use Svelte, but I'm afraid there are too few examples, guides, etc with this framework.

**Comment by lamtev** [comment]
> but I'm afraid there are too few examples, guides, etc with this framework.

Good point

**Comment by lamtev** [comment]
2. What Dependency Management System should we use? Is there a default one in frontend world? Or maybe several variants available?

**Comment by vaddya** [comment]
> 1. What Dependency Management System should we use? Is there a default one in frontend world? Or maybe several variants available?

Good question, I'll add this to the wiki. Short answer -- I would rather use `npm`, although `yarn` is an option to consider. I also forgot to mention the build system for JS -- `webpack` is the de-facto standard in the frontend world.

**Comment by lamtev** [comment]
approve
