### ISSUE TITLE
Choose CSS framework

### ISSUE THREAD

**Issue by vaddya** [ACCULA/accula#17]
There is a [huge](https://github.com/troxler/awesome-css-frameworks) number of CSS frameworks and most of them have similar concepts and components. 

I suggest choosing between [Bootstrap](https://getbootstrap.com) and [Bulma](https://bulma.io). First is more popular and has a big community, while the latter is more modern and easier to use (see [comparison](https://bulma.io/alternative-to-bootstrap/)). It is worth noting other possible options: [Materialize](https://materializecss.com/) and [Foundation](https://get.foundation/). All of them have good React integration ([1](https://www.npmjs.com/package/react-bootstrap), [2](https://www.npmjs.com/package/react-bulma-components), [3](https://www.npmjs.com/package/react-materialize), [4](https://www.npmjs.com/package/react-foundation)).

I am inclined to Bulma.

**Comment by lamtev** [comment]
According to bulma-react [weakly download count](https://www.npmjs.com/package/react-bulma-components) it is not as popular as other css frameworks when using react

**Comment by lamtev** [comment]
> while the latter is more modern and easier to use [Bulma]

Have you checked that statement? Are you agree with this?

**Comment by vaddya** [comment]
Bootstrap has no competitors in terms of popularity. Bulma is not so widely used, but its popularity is growing. Bulma also has beautiful components and it's easy to use %). We can start with Bulma and switch to Bootstrap if there would be any trouble.

**Comment by lamtev** [comment]
Nice! Since we are hipsters, let's use Bulma!

**Comment by lamtev** [comment]
What about react-bulma documentation? I heard it's so much shitty

**Comment by vaddya** [comment]
Totally agree with use, let's rollback to Bootstrap, it has amazing doc.
