### ISSUE TITLE
Investigate Code Clone detection techniques

### ISSUE THREAD

**Issue by VanyaKrylov** [ACCULA/accula#4]
[Link](https://gist.github.com/VanyaKrylov/b12481ff9ede6f92343b864b0dd90b7e)

**Comment by vaddya** [comment]
> [Link](https://gist.github.com/VanyaKrylov/b12481ff9ede6f92343b864b0dd90b7e)

It would be nice to move this to our wiki

**Comment by lamtev** [comment]
> > [Link](https://gist.github.com/VanyaKrylov/b12481ff9ede6f92343b864b0dd90b7e)
> 
> It would be nice to move this to our wiki

I’d say it’s required

**Comment by vaddya** [comment]
@VanyaKrylov ping

**Comment by VanyaKrylov** [comment]
**UPD**: Clone detection technique based on suffix tree was chosen and implemented ([PR](https://github.com/ACCULA/accula/pull/112)). Although the solution based on suffix tree does provide the desired functionality, there are several challenges with it, such as persistence. Thus it is suggested to continue investigation on other existing code clone detection solutions

**Comment by lamtev** [comment]
Resolved
